version: '3.3'

services:
  db:
    networks:
      - videoteca_default-network
    image: postgres:14
    environment:
      - POSTGRES_DB=videoteca  
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - /var/lib/postgresql/backupsVideoteca:/docker-entrypoint-initdb.d
      - videoteca-data:/var/lib/postgresql/data

  rh:
    networks:
      - videoteca_default-network
    image: postgres:14
    environment:
      - POSTGRES_DB=recursoshumanos
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5432"
    volumes:
      - /var/lib/postgresql/backupsRh:/docker-entrypoint-initdb.d
      - recursos-humanos-data:/var/lib/postgresql/data

  web:
    networks:
      - videoteca_default-network
    build:
      context: .
      dockerfile: Dockerfile
    image: django:latest
    command: python manage.py runserver 0.0.0.0:8085
    #command: ["./wait-for-it.sh", "db:5433", "rh:5434", "python", "manage.py", "runserver", "0.0.0.0:8085"]
    volumes:
      - .:/app
    ports:
      - "8085:8085"
    depends_on:
      - db
      - rh
    environment:
      - DEBUG=False
    restart: always

volumes:
  videoteca-data:
  recursos-humanos-data:

networks:
  videoteca_default-network:
    driver: bridge
